source: ./www
lang: en-GB
google_analytics: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments