source: ./www
lang: en-GB
google_analytics: false

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments