liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

source: ./www
lang: en-GB
google_analytics: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"




markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments
  syntax_highlighter_opts:
    block:
      line_numbers: true